name: Daily

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  
jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - name: Get latest code
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Destroy old stuff
      run: dotnet run --project MyTwitterManager
      env:
        TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
        TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
        TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        TWITTER_SCREEN_NAME: ${{ secrets.TWITTER_SCREEN_NAME }}
